
import React from 'react';
import { Mail, Linkedin, ExternalLink, ShieldCheck, Award, Code2, Heart, HelpCircle, MessageCircle } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';

const SUPPORT_EMAIL = "aayansah17@gmail.com";
const LINKEDIN_URL = "https://www.linkedin.com/in/aboutakashsah/";

const Support: React.FC = () => {
  const { user } = useAuth();

  const contactSupport = () => {
      window.location.href = `mailto:${SUPPORT_EMAIL}?subject=Support Request - RevenuePro&body=User ID: ${user?.uid}`;
  };

  return (
    <div className="p-6 md:p-12 max-w-5xl mx-auto pb-24 font-sans">
      <h1 className="text-3xl font-bold text-slate-900 mb-2">Help & Support</h1>
      <p className="text-slate-500 mb-10 text-lg">Connect with the team and learn about the creators.</p>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left Col: Contact & Disclaimer */}
        <div className="lg:col-span-1 space-y-6">
            
            {/* Contact Card */}
            <div className="bg-white p-8 rounded-[24px] border border-slate-200 shadow-sm hover:shadow-md transition-shadow">
                <div className="w-14 h-14 bg-blue-50 rounded-2xl flex items-center justify-center text-blue-600 mb-6">
                    <MessageCircle className="w-7 h-7" />
                </div>
                <h3 className="font-bold text-slate-900 text-xl mb-3">Need Assistance?</h3>
                <p className="text-slate-500 mb-8 leading-relaxed">
                    Facing issues with calculations or have a feature request? Reach out directly to our support team.
                </p>
                <button 
                    onClick={contactSupport}
                    className="w-full bg-slate-900 hover:bg-slate-800 text-white font-bold py-4 rounded-xl flex items-center justify-center gap-2 transition-all shadow-lg shadow-slate-200 hover:-translate-y-1"
                >
                    <Mail className="w-5 h-5" /> Contact Support
                </button>
            </div>

            {/* Legal / Disclaimer (Moved Here) */}
            <div className="bg-slate-50 p-8 rounded-[24px] border border-slate-200/60">
                <div className="flex items-center gap-3 mb-6">
                    <div className="bg-slate-200 p-2.5 rounded-xl text-slate-600">
                        <ShieldCheck className="w-6 h-6" />
                    </div>
                    <h3 className="font-bold text-slate-800 text-lg">Legal Disclaimer</h3>
                </div>
                <div className="space-y-4 text-xs text-slate-500 leading-relaxed text-justify font-medium">
                    <p>
                        <strong className="text-slate-700 block mb-1">For Estimation Only</strong> The figures generated by this application are estimates based on user inputs and standard industry formulas. They should not be considered as guaranteed results.
                    </p>
                    <p>
                        <strong className="text-slate-700 block mb-1">Not Financial Advice</strong> This tool does not constitute professional financial, legal, or investment advice. Users should independently verify all calculations before making business decisions.
                    </p>
                    <p>
                        <strong className="text-slate-700 block mb-1">No Liability</strong> The developer (Akash Sah) accepts no liability for any loss or damage arising from the use of this software. By using this tool, you agree to these terms.
                    </p>
                </div>
            </div>

        </div>

        {/* Right Col: Founder Profile (Moved Here) */}
        <div className="lg:col-span-2 h-full">
            <div className="bg-white rounded-[32px] border border-slate-200 shadow-xl shadow-slate-200/50 overflow-hidden relative group h-full flex flex-col">
                <div className="absolute top-0 right-0 w-80 h-80 bg-slate-50 rounded-bl-[200px] -mr-20 -mt-20 z-0 group-hover:bg-blue-50 transition-colors duration-700"></div>
                
                <div className="p-8 md:p-12 relative z-10 flex-1 flex flex-col">
                    <div className="flex flex-col sm:flex-row items-start justify-between mb-10 gap-6">
                        <div className="flex items-center gap-6">
                            <div className="w-24 h-24 rounded-3xl bg-slate-900 flex items-center justify-center text-white font-bold text-3xl shadow-2xl shadow-slate-400 ring-8 ring-white">
                                AS
                            </div>
                            <div>
                                <h3 className="font-bold text-slate-900 text-3xl mb-1">Akash Sah</h3>
                                <div className="flex items-center gap-2 text-sm text-blue-600 font-bold uppercase tracking-wide bg-blue-50 w-fit px-3 py-1 rounded-full">
                                    <Award className="w-4 h-4" /> Founder & Lead Engineer
                                </div>
                            </div>
                        </div>
                        <a 
                            href={LINKEDIN_URL}
                            target="_blank" 
                            rel="noopener noreferrer"
                            className="p-3 bg-[#0077b5] text-white rounded-xl hover:bg-[#006396] transition-colors shadow-lg hover:scale-105 transform duration-200"
                            title="Connect on LinkedIn"
                        >
                            <Linkedin className="w-6 h-6" />
                        </a>
                    </div>

                    <div className="space-y-8 mb-12 flex-1">
                         <p className="text-slate-600 text-lg leading-relaxed font-light">
                            <span className="text-5xl float-left mr-3 mt-[-10px] text-slate-200 font-serif">"</span>
                            A visionary technologist and entrepreneur, Akash is dedicated to transforming the hospitality industry through intelligent software solutions. With deep expertise in Full-Stack Architecture and Financial Analytics, he built <strong>Hotel Revenue Pro</strong> to bridge the gap between complex financial modeling and intuitive user experience.
                        </p>
                        <p className="text-slate-600 text-lg leading-relaxed font-light">
                            Driven by a passion for clean code and user-centric design, Akash continues to push the boundaries of SaaS innovation, empowering business owners to make smarter, data-backed investment decisions.
                        </p>
                    </div>
                    
                    <div className="mt-auto pt-10 border-t border-slate-100 flex flex-wrap gap-4">
                         <div className="flex items-center gap-2 px-5 py-3 bg-slate-50 rounded-2xl text-slate-700 text-sm font-bold border border-slate-100">
                            <Code2 className="w-4 h-4 text-slate-400" /> Full Stack Dev
                         </div>
                         <div className="flex items-center gap-2 px-5 py-3 bg-slate-50 rounded-2xl text-slate-700 text-sm font-bold border border-slate-100">
                            <Heart className="w-4 h-4 text-slate-400" /> UI/UX Design
                         </div>
                         <div className="flex items-center gap-2 px-5 py-3 bg-slate-50 rounded-2xl text-slate-700 text-sm font-bold border border-slate-100">
                             <HelpCircle className="w-4 h-4 text-slate-400" /> Problem Solver
                         </div>
                         <a 
                            href={LINKEDIN_URL}
                            target="_blank" 
                            rel="noopener noreferrer"
                            className="ml-auto flex items-center gap-2 text-blue-600 font-bold hover:underline py-3"
                        >
                            View Full Profile <ExternalLink className="w-4 h-4" />
                        </a>
                    </div>
                </div>
            </div>
        </div>

      </div>

      <div className="mt-20 pt-8 border-t border-slate-200 text-center">
        <p className="text-slate-500 text-sm font-medium flex items-center justify-center gap-2">
            <Code2 className="w-4 h-4" />
            Designed & Developed by <span className="text-slate-900 font-bold">Akash Sah</span>
        </p>
        <p className="text-slate-400 text-xs mt-2">© {new Date().getFullYear()} All rights reserved by Akash Sah.</p>
      </div>
    </div>
  );
};

export default Support;
